FROM python:3.8-slim as base
WORKDIR /app
CMD echo 'appelsap' > images/test.txt \
&& ls \
&& cd images \
&& ls
# CMD echo 'appelsap' > images/test.txt
# CMD cd images && ls && cat test.txt
# CMD 'echo "test" > images/test.txt'
#RUN python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl
# RUN pip install "tensorflow" \
#     && pip install "tensorflow_hub" \
#     # && pip install "tensorflow-hub[make_image_classifier]"
# EMTRYPOINT ["python"']